data:
  name: 'SparsePixelMapNOvA'
  filedir: '/data/mp5/preselection'
  t_v_split: 0.05

model:
  name: 'MobileNet'
  D: 2
  alpha: 0.25
  depth: 1
  classes: 3
  loss_func: 'CrossEntropyLoss'
  optimizer: 'AdamW'
  learning_rate: 1.e-4
  weight_decay: 0.01
  step_size: 1 # How many epochs between LR reduction
  gamma: 0.8 # Factor to reduce learning rate by
  class_names: ['numu','nue','nc']

data_loader:
  batch_size: 1000
  num_workers: 3

trainer:
  benchmark: False
  device: 0 # Which GPU to use
  n_epochs: 20
  max_iters_train: None
  max_iters_eval:  None
  train_name:  'train1'
  summary_dir: '/scratch/SparseNOvA/summary'
  output_dir:  '/scratch/SparseNOvA/params'

inference:
  max_images: 100 # Maximum number of images to process
  event_display: True # Whether to draw event displays
  confusion: False # Whether to draw a confusion matrix
  state_dict: None # Replace this with a string path to a trained .pth.tar file after training! They're written to params/checkpoints
