data:
  name: 'SparsePixelMap3D'
  root: '/data/3d'
  trainfiles: 'showers1'   #'MCProd4a_SPM'  
  #'2GeVpBarExample' #
  t_v_split: 0.05

process:
  processes: 50
  max_files: 10000
  pre_transform: None
  voxel_size: 1
  #feat_norm: [1.e-5, 1.e-5, 1.e-5, 6.25e-4, 1.667e-3, 1.429e-3, 5.e-2]
  feat_norm: [1.e-5, 1.e-5, 1.e-5, 1.429e-3,1.667e-3,1.429e-3, 5.e-2]

model:
  name: 'ASPP_Panoptic'
  #'MinkowskiSeg' #
  n_dims: 3
  rate: [6,12,18]
  extent: 6000 # Maximum dimension of pixel map
  input_feats: 7
  n_feats: 32 # Number of features
  unet_depth: 10 
  res_blocks: True # Whether to use residual blocks in unet

  instance_segmentation: 'True'
  loss_params:
    SEMANTIC: 
      func: 'categorical_cross_entropy'
    CENTER:
      func: 'cross_entropy'
    OFFSET:
      func: 'L1Loss' 
  
  arrange_data: 'arrange_sparse_minkowski'
  arrange_truth: 'sparse_panoptic_truth'

  activation_params:
    activation: 'mish'
    LeakyReLU:
      negative_slope: 0.1

  optimizer_params:
    optimizer: 'SGD'
    AdamW:
      lr: 1.e-2
      weight_decay:     0.01
    Ranger:
      lr:               1.e-3
      alpha:            0.5
      k:                6
      N_sma_threshhold: 5
      betas:            [ 0.95, 0.999 ]
      eps:              1.e-5
      weight_decay:     0
      use_gc:           True
      gc_conv_only:     False
    SGD:
      lr:               1.e-3
      momentum:         0.9

  scheduler_params:
    scheduler: 'CyclicLR'
    ReduceLROnPlateau:
      factor: 0.5
      patience: 5
    StepLR:
      step_size: 3 
      gamma: 0.1
      verbose: True 
    CyclicLR:
      base_lr: 1.e-4
      max_lr: 6.e-4
      step_size_up: 3000
      step_size_down: 3000
      mode: 'triangular'
      gamma: 1.0
      verbose: False


  n_classes: 8 

  metric_params:
    metrics: 'SemanticSegmentation'
    include_batch_metrics: True
    SemanticSegmentation:
      class_names: ['shower','delta','diffuse','kaons','michel','hip','mu','pi']

data_loader:
  batch_size: 30 
  num_workers: 0 

trainer:
  device: 5 # Which GPU to use
  n_epochs: 20
  empty_cache: 1
  max_iters_train: None 
  max_iters_eval:  None 
  summary_dir: 'summary/3d/debugging/feat_test/SemSeg32F_CyclicLR_NO_ASPP_mish_dropout_1-6e-4'
  output_dir: '/data/3d/params/debugging/feat_test/SemSeg32F_CyclicLR_NO_ASPP_mish_dropout_1-6e-4' 

inference:
  max_images: 300 # Maximum number of images to process
  event_display: False # Whether to draw event displays
  confusion: True # Whether to draw a confusion matrix
  state_dict: None 
  
