data:
  name: "simple"
  path: "/data/hit2d/processed-flav-shower"
  t_v_split: 0.05

trainer:
  device: 2
  batch_size: 4
  n_epochs: 100
  empty_cache: 1 # How many iterations between calls to empty GPU memory cache
  train_name: "with-6-twoloss"
  summary_dir: "/scratch/GraphDUNE/summary/edgefeats"
  output_dir: "/scratch/GraphDUNE/params/edgefeats"

model:
  name: "TwoLoss"
  input_dim: 9
  hidden_dim: 64
  output_dim: 3
  n_iters: 4
  how: "classwise"
  stacks: True
  edgefeats: True
  loss_params:
    func: "twoloss"

  arrange_data: "arrange_graph"
  arrange_truth: "arrange_graph"

  scheduler_params:
    scheduler: "ReduceLROnPlateau"
    ReduceLROnPlateau:
      factor: 0.5
      patience: 3
    StepLR:
      step_size: 5
      gamma: 0.8

  activation_params:
    activation: "mish"

  optimizer_params:
    optimizer: "AdamW"
    AdamW:
      lr: 1.e-4
      weight_decay: 0.01
    Fromage:
      lr: 0.01
    SGD:
      lr: 0.01
      
  metric_params:
    metrics: "Graph"
    include_batch_metrics: True
    Graph:
      class_names: [ "false", "shower", "muon", "hadronic" ]

inference:
  state_dict: "params/deep-classwise-adamw-2/checkpoints/model_checkpoint_GNNDeepMultiHead_113412_4956229998_hewesje.best.pth.tar"
