data:
  name: 'simple'
  path: '/data/hit2d/processed-flav-shower'
  t_v_split: 0.05

trainer:
  device: 7
  batch_size: 16
  n_epochs: 50
  train_name: 'denseshower1'
  summary_dir: '/scratch/GraphDUNE/summary'
  output_dir: '/scratch/GraphDUNE/params'

model:
  name: 'MultiHead'
  input_dim: 9
  hidden_dim: 64
  classes: 4
  n_iters: 4
  loss_params:
    func: 'CrossEntropyLoss'
  arrange_data: 'arrange_graph'
  arrange_truth: 'arrange_graph'

  step_size: 5
  gamma: 0.8

  activation_params:
    activation: 'mish'

  optimizer_params:
    optimizer: 'AdamW'
    AdamW:
      lr: 1.e-4
      weight_decay: 0.01
    Fromage:
      lr: 0.01
      
  metric_params:
    metrics: 'Classification'
    include_batch_metrics: False
    Classification:
      class_names: [ 'false', 'shower', 'muon', 'hadronic' ]
